global using Object = UnityEngine.Object;
global using Random = UnityEngine.Random;
global using Console = WorldBoxConsole.Console;
global using OptionData = UnityEngine.UI.Dropdown.OptionData;
global using ButtonClickedEvent = UnityEngine.UI.Button.ButtonClickedEvent;
global using MovementType = UnityEngine.UI.ScrollRect.MovementType;
global using XuanJianVNext.Core;
global using XuanJianVNext.Data.Archive;
global using XuanJianVNext.Data.CaiQi;
global using XuanJianVNext.Data.Death;
global using XuanJianVNext.Data.Events;
global using XuanJianVNext.Data.FaBao;
global using XuanJianVNext.Data.Family;
global using XuanJianVNext.Data.GongFa;
global using XuanJianVNext.Data.Rules;
global using XuanJianVNext.Systems.ActorSystem;
global using XuanJianVNext.Systems.Aptitude;
global using XuanJianVNext.Systems.Archive;
global using XuanJianVNext.Systems.CaiQi;
global using XuanJianVNext.Systems.Chronicle;
global using XuanJianVNext.Systems.Cultivation;
global using XuanJianVNext.Systems.Death;
global using XuanJianVNext.Systems.Events;
global using XuanJianVNext.Systems.FaBao;
global using XuanJianVNext.Systems.Family;
global using XuanJianVNext.Systems.GongFa;
global using XuanJianVNext.Systems.HighRealm;
global using XuanJianVNext.Systems.Warehouse;
global using XuanJianVNext.Systems.ZongMen;
global using XuanJianVNext.UI.ActorInfo;
global using XuanJianVNext.UI.Chronicle;
global using XuanJianVNext.UI.Family;
global using XuanJianVNext.UI.ZongMen;
